name: Bug Report
description: Report a bug with necessary details.
labels: ["bug"]  # Default label
body:
  - type: markdown
    attributes:
      value: "### 🐞 Bug Report Form"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the bug.
      placeholder: "Describe the issue in detail..."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity of the issue.
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level.
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Select the current status of this issue.
      options:
        - Open
        - In Progress
        - Dev Fixed
        - Test
        - Retesting in progress
        - Closed
        - Reopened
        - Deferred
        - Invalid
        - Duplicate
    validations:
      required: true
